version: "3.9"

services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "3001:3001"
    volumes:
      - ./fastapi:/app
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/fastapi/sa.json
    command: uvicorn main:app --host 0.0.0.0 --port 3001 --reload

  react:
    build:
      context: ./react
      dockerfile: Dockerfile
    container_name: react_app
    ports:
      - "80:80"
    restart: always
