name: Run Shell Script and Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Decode Google Service Account Key
        run: |
          set -x
          abc=$(echo -n '{"name":"Alice","age":30}' | base64)
          echo $abc
          echo "ENCODED_SECRET=$abc" >> $GITHUB_ENV
        shell: bash

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Tag and push React image
        run: |
          docker tag nxgenailab_site_react:latest ${{ secrets.DOCKERHUB_USERNAME }}/nxgenailab_site_react:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nxgenailab_site_react:latest

      - name: Tag and push FastAPI image
        run: |
          docker tag nxgenailab_site_fastapi:latest ${{ secrets.DOCKERHUB_USERNAME }}/nxgenailab_site_fastapi:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/nxgenailab_site_fastapi:latest